// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9HdW8oJSCxrKyYsVaZU4IdVYdAi-U8YI',
    appId: '1:940862132636:web:211ecbfb71821e97463859',
    messagingSenderId: '940862132636',
    projectId: 'quickdeal-89586',
    authDomain: 'quickdeal-89586.firebaseapp.com',
    storageBucket: 'quickdeal-89586.firebasestorage.app',
    measurementId: 'G-J5YB4HMSDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs9ahr7LTJG2qjRB9Yk1g-F6DagBtHFXs',
    appId: '1:940862132636:android:a2b185509db4e96a463859',
    messagingSenderId: '940862132636',
    projectId: 'quickdeal-89586',
    storageBucket: 'quickdeal-89586.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4PaHnmeimzekrmWY11oAya9bt7U2BSQI',
    appId: '1:940862132636:ios:6740d29384d85ccb463859',
    messagingSenderId: '940862132636',
    projectId: 'quickdeal-89586',
    storageBucket: 'quickdeal-89586.firebasestorage.app',
    iosBundleId: 'com.example.quickdeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4PaHnmeimzekrmWY11oAya9bt7U2BSQI',
    appId: '1:940862132636:ios:6740d29384d85ccb463859',
    messagingSenderId: '940862132636',
    projectId: 'quickdeal-89586',
    storageBucket: 'quickdeal-89586.firebasestorage.app',
    iosBundleId: 'com.example.quickdeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9HdW8oJSCxrKyYsVaZU4IdVYdAi-U8YI',
    appId: '1:940862132636:web:0b538d352ac0d2af463859',
    messagingSenderId: '940862132636',
    projectId: 'quickdeal-89586',
    authDomain: 'quickdeal-89586.firebaseapp.com',
    storageBucket: 'quickdeal-89586.firebasestorage.app',
    measurementId: 'G-6FJE05B77V',
  );
}
